const AUTH_LOGOUT = "AUTH_LOGOUT";
const AUTH_CREATE_ERROR_MESSAGE = "AUTH_CREATE_ERROR_MESSAGE";
const AUTH_REMOVE_ERROR_MESSAGE = "AUTH_REMOVE_ERROR_MESSAGE";
const AUTH_REFRESH_TOKEN = "AUTH_REFRESH_TOKEN";
const AUTH_FETCH_PROFILE = "AUTH_FETCH_PROFILE";
const AUTH_FETCH_TOKENS = "AUTH_FETCH_TOKENS";
const AUTH_RESET = "AUTH_RESET";
const AUTH_NEW_PASSWORD = "AUTH_NEW_PASSWORD";
const AUTH_LOADED_NEW_PASSWORD = "AUTH_LOADED_NEW_PASSWORD";

export default {
  AUTH_LOGOUT,
  AUTH_CREATE_ERROR_MESSAGE,
  AUTH_REMOVE_ERROR_MESSAGE,
  AUTH_REFRESH_TOKEN,
  AUTH_FETCH_PROFILE,
  AUTH_FETCH_TOKENS,
  AUTH_RESET,
  AUTH_NEW_PASSWORD,
  AUTH_LOADED_NEW_PASSWORD,
};
