const AUTH_LOGOUT = "AUTH_LOGOUT";
const AUTH_CREATE_ERROR_MESSAGE = "AUTH_CREATE_ERROR_MESSAGE";
const AUTH_REMOVE_ERROR_MESSAGE = "AUTH_REMOVE_ERROR_MESSAGE";
const AUTH_REFRESH_TOKEN = "AUTH_REFRESH_TOKEN";
const AUTH_FETCH_PROFILE = "AUTH_FETCH_PROFILE";
const AUTH_FETCH_TOKENS = "AUTH_FETCH_TOKENS";

export default {
  AUTH_LOGOUT,
  AUTH_CREATE_ERROR_MESSAGE,
  AUTH_REMOVE_ERROR_MESSAGE,
  AUTH_REFRESH_TOKEN,
  AUTH_FETCH_PROFILE,
  AUTH_FETCH_TOKENS,
};
