const COMMON_SET_MESSAGE = "COMMON_SET_MESSAGE";
const COMMON_REMOVE_MESSAGE = "COMMON_REMOVE_MESSAGE";
const COMMON_TOGGLE_SPINNER = "COMMON_TOGGLE_SPINNER";

export default {
  COMMON_SET_MESSAGE,
  COMMON_REMOVE_MESSAGE,
  COMMON_TOGGLE_SPINNER,
};
