const RESET_FIGURES = "RESET_FIGURES";
const SET_FIGURES = "SET_FIGURES";
const SELECT_FIGURE = "SELECT_FIGURE";
const MOVE_FIGURE = "MOVE_FIGURE";

export default {
  RESET_FIGURES,
  SET_FIGURES,
  SELECT_FIGURE,
  MOVE_FIGURE,
};
